const mongoose = require("mongoose");

const sahabaSchema = mongoose.Schema({
  nom: { type: String },
  prénom: { type: String },
  naissance: {
    type: String,
    enum: ["Mecqua", "Médine", "Taif", "Perse", "Abyssinie", "Autres lieux"],
  },
  genre: {
    type: String,
    enum: ["Homme", "Femme"],
  },
  conversion: {
    type: String,
    enum: [
      "De l’an 1 de la Révélation",
      "An 2",
      "An 3",
      "An 4",
      "An 5",
      "An 6",
      "An 7",
      "An 8",
      "An 9",
      "An 10 de la Révélation",
      "An 1 de l’Hégire",
      "An 2 de l’Hégire",
      "An 3 de l’Hégire",
      "An 4 de l’Hégire",
      "An 5 de l’Hégire",
      "An 6 de l’Hégire",
      "An 7 de l’Hégire",
      "An 8 de l’Hégire",
      "An 9 de l’Hégire",
      "An 10 de l’Hégire",
      "An 11 de l’Hégire",
      "An 12 de l’Hégire",
      "An 13 de l’Hégire",
    ],
  },
  parenté: {
    type: [String],
    enum: [
      "Aucun",
      "Epouse",
      "Fils/fille",
      "Oncle/tante (quel que soit le degré)",
      "Cousin/cousine (quel que soit le degré)",
      "Beau-frère/belle-sœur",
      "Gendre/belle-fille",
      "Beau-père/belle-mère",
      "Frère/sœur (germain, consanguin, utérin, de lait)",
      "Petit-fils/petite-fille",
      "Neveu/nièce (quel que soit le degré)",
    ],
  },
  fonction: {
    type: [String],
    enum: [
      "Aucune",
      "Gouverneur",
      "Imama",
      "Juge",
      "Commandant de l’armée",
      "Porte étendard",
      "Muezzin",
      "Enseignant",
      "Émissaire",
      "Fonctionnaire de l’état",
      "Scribe",
    ],
  },
  ethnie: {
    type: String,
    enum: ["Arabe", "Perse", "Abyssin", "Autre"],
  },
  bataille: {
    type: [String],
    enum: [
      "Aucune",
      "Expédition de Waddan et d'Abwa",
      "Expédition de Bowât",
      "Expédition d'Uchayra",
      "Première expédition de Badr",
      "Expédition de Batn Nakhl",
      "Batailles de Badr",
      "Expédition de Kodr",
      "Expédition contre les Banu Qaynuqa",
      "Expédition de Sawiq",
      "Expédition de Dhu Amarr",
      "Expédition de Qarada",
      "Expédition d'Uhud",
      "Expédition de Raji",
      "Expédition contre les Banu Nadhir",
      "Expédition de Dhat ar-Riqa",
      "Expédition de Dawma al-Jandal",
      "Bataille du Fossé (Al Khandaq)",
      "Expédition contre les Banu Qurayza",
      "Expédition contre les Banu Lihyân",
      "Expédition de Dhou-Qoroud",
      "Expédition contre les Banu Mustaliq",
      "Expédition de Hudaybiya",
      "Expédition de Khaïbar",
      "Expédition de Fadak",
      "Expédition de Wadi al-Qora",
      "Bataille de Mu'ta",
      "Conquête de la Mecque : Fatah Macqua",
      "Expédition de Hunayn",
      "Expédition de Ta'if",
      "Expédition de Tabuk",
    ],
  },
  métier: {
    type: [String],
    enum: ["Commerçant", "Agriculteur-éleveur", "Calife", "Fonctionnaire"],
  },

  émigration: {
    type: [String],
    enum: [
      "1ère émigration en Abyssinie",
      "2e émigration en Abyssinie",
      "Médine",
    ],
  },
  serment: {
    type: [String],
    enum: [
      "Aucun",
      "Le premier d’Al ‘Aqaba",
      "Le deuxième d’Al ‘Aqaba",
      "Le pacte d’al hudaybiya",
      "Bay’atu ridwan",
    ],
  },
  catégorie: {
    type: String,
    enum: ["Muhajjirs", "Ansars", "Autre"],
  },
  bienfait: {
    type: [String],
    enum: ["Une invocation", "La promesse du paradis", "Autre"],
  },
  verset: { type: Boolean },
  résumé: { type: String },
});

module.exports = mongoose.model("Sahaba", sahabaSchema);
